apiVersion: v1
kind: Deployment
metadata:
  name: k8sdemo
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: k8sdemo
    spec:
      containers:
      - name: k8sdemo
        image: mvdmeij/k8sdemo:1
        ports:
        - containerPort: 8080
