apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8sdemo
  labels:
    app: k8sdemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8sdemo
  template:
    metadata:
      labels:
        app: k8sdemo
    spec:
      containers:
      - name: k8sdemo
        image: mvdmeij/k8sdemo:1
        ports:
        - containerPort: 80
